{
  'name': 'Modulo Administracion Estudiantil',
  'version': '1.1.2',
  'author': 'Anthony Escobar / AE-Solutions',
  'category': 'Education',
  'depends': ['base','web'],
  'data': [
      'security/roles.xml',
      'security/auth.xml',
      'security/ir.model.access.csv',
      'views/teacher.xml',   
      'views/subject.xml', 
      'views/classroom.xml',
      'views/schedule.xml', 
      'views/student.xml',
      'views/exam.xml',
      'views/result.xml',
      'views/menu.xml',
      'wizard/student_transcript_wizard.xml',
      'wizard/student_schedule_wizard.xml',
      'data/sequence_card.xml',
      'data/data_classroom.xml',
      'data/data_student.xml',
      'data/data_teacher.xml',
      'data/data_subject.xml',
      'data/data_schedule.xml',
      'data/data_exam.xml',
      'data/data_result.xml',
      ],
  'demo': [
        'data/data_classroom.xml',
        'data/data_student.xml',
        'data/data_teacher.xml',
        'data/data_subject.xml',
        'data/data_schedule.xml',
        'data/data_exam.xml',
        'data/data_result.xml',
    ],
  'installable': True,
  'application': True,
  'external_dependencies': {
        'python': ['reportlab'],
    },
   'images': ['static/description/AE_Solutions_Logo.png'],
}
