{
  'name': 'Modulo: administracion estudiantil',
  'version': '1.0',
  'author': 'Anthony Escobar / AE-Solutions',
  'category': 'Education',
  'depends': ['base','web'],
  'data': [
    'security/ir.model.access.csv',
    'security/roles.xml',
    'views/classroom.xml',
    'views/subject.xml',
    'views/student.xml',
    'views/menu.xml',
    #'data/demo_data.xml',
    'data/sequence_card.xml',
  ],
  'demo': ['demo/demo_data.xml'],
  'installable': True,
  'application': True,
}
